### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by mayday77** [Moham3dRiahi/Th3inspector#1]
Hello there 
After executing DOMAIN WHOIS 
got a result 
malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "<?xml version="1.0" ...") at /usr/share/Th3inspector/Th3inspector.pl line 726, <STDIN> line 11.

------------------------------------------
Linux kali 4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU/Linux

**Comment by Moham3dRiahi** [comment]
apt-get install make && cpan install JSON
