### ISSUE TITLE
Exception while running tool.

### ISSUE THREAD

**Issue by arbazkiraak** [Moham3dRiahi/Th3inspector#10]
Please check the Following Log 👍 
--------------------------------------------------------
┌─[root@kali]─[~/Desktop/Th3inspector]
└──╼ #ls
LICENSE  README.md  Th3inspector.pl  config  install.sh  update.sh
┌─[root@kali]─[~/Desktop/Th3inspector]
└──╼ #perl Th3inspector.pl -h
Can't locate JSON.pm in @INC (you may need to install the JSON module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at Th3inspector.pl line 18.
BEGIN failed--compilation aborted at Th3inspector.pl line 18.

**Comment by Moham3dRiahi** [comment]
cpan install JSON
