### ISSUE TITLE
Th3inspector not working 

### ISSUE THREAD

**Issue by kamru** [Moham3dRiahi/Th3inspector#11]
When i choose any number of this tool could not work.
Here is a screen shot 
https://mega.nz/#!fqYUXawK!l9_ukjOiuxn2RwI5hvybdobN6D4g9Ig0ksArgKZN89k

**Comment by d0pp1364n63r** [comment]
You need to put a "0" in front of the 2 as in "02" That should fix

**Comment by kamru** [comment]
d0pp1364n63r

**Comment by kamru** [comment]
Thanks man its work

**Comment by VictorH4C7** [comment]
Kamru after chosen the number I want it kept showing me there is a problem why
