### ISSUE TITLE
There Is A Problem

### ISSUE THREAD

**Issue by d0pp1364n63r** [Moham3dRiahi/Th3inspector#12]
Code works very sporadicly
Option 02;
Enter Phone #; 
No matter what input it give the same error: "There Is A Problem" Then closes the script
Tested with Ubuntu 16.04 && 18.04 && Kali 2018.1/2
Th3inspector v. 1.9

**Comment by Moham3dRiahi** [comment]
This was fixed a while ago, please update to the latest version on github

Execute the following command on your terminal:
git pull

or clone the repo again:
git clone https://github.com/Moham3dRiahi/Th3inspector.git

**Comment by Kongledyret** [comment]
Hi, 
I'm getting the same error on all the different options. 
Tested with Ubuntu 16.04 & OSX High Sierra 10.3.6

**Comment by ZuhairAhamed** [comment]
For the option 2(phone number information) its showing an error "There Is A Problem" for all kind of input

**Comment by C0ntr07** [comment]
Getting the same issue on a new / updated installation.


 [+] There Is A Problem

 [1] Checking The Connection
 [2] Enter Phone Number Without +/00
 [3] Check If Phone Number Exists
root@kali:~/tools/Th3inspector#

**Comment by C0ntr07** [comment]
Has never worked for me.

Th3inspector 1.9
Kali 4.18.0
amd 64
Debian 4.18.10

**Comment by ajmankar** [comment]
whenever i type `02` it asks to type mobile number but after typing the number it gives the error

[+] There Is A Problem

 [1] Checking The Connection
 [2] Enter Phone Number Without +/00
 [3] Check If Phone Number Exists
$

what should i do with it pls help

**Comment by gursharansinghgarhi** [comment]
not a single 
 option working

**Comment by VictorH4C7** [comment]
Why is it showing there is a problem

**Comment by hackerbabahb93** [comment]
hello i need help. please how can i solve this problem?

[+] There Is A Problem

[1] Checking The Connection
[2] Enter Phone Number Without +/00
[3] Check If Phone Number Exists

**Comment by rednikisfun** [comment]
I have the same issue, is there any solution yet?

**Comment by vijay222-del** [comment]
How slove this "BEGIN failed--compilation aborted at Th3inspector.pl line 5". showing in termux please tell me how to fix
