### ISSUE TITLE
Compilation aborted ERROR

### ISSUE THREAD

**Issue by kali64amd** [Moham3dRiahi/Th3inspector#13]
Hi there

I'm trying to install on Kali machine however I'm getting this issue so please advise. 
 [+] Checking directories...
 [+] A Directory Th3inspector Was Found! Do You Want To Replace It? [Y/n]:
y
 [+] Installing ...
 [+] Creating Symbolic Link ...
 [+] Tool Successfully Installed And Will Start In 5s!
 [+] You can execute tool by typing Th3inspector
Can't locate JSON.pm in @INC (you may need to install the JSON module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.2 /usr/local/share/perl/5.26.2 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/Th3inspector/Th3inspector.pl line 18.
BEGIN failed--compilation aborted at /usr/share/Th3inspector/Th3inspector.pl line 18.

**Comment by Moham3dRiahi** [comment]
Execute this command line to fix the problem
`cpan install JSON`

**Comment by Moham3dRiahi** [comment]
Execute this command line to fix the problem
`cpan install JSON`
