### ISSUE TITLE
Hello i have a problem

### ISSUE THREAD

**Issue by TomixVoid** [Moham3dRiahi/Th3inspector#15]
Can't locate HTTP/Request.pm in @INC (you may need to install the HTTP::Request module) (@INC contains: /data/data/com.termux/files/usr/lib/perl5/site_perl/5.26.2/arm-android /data/data/com.termux/files/usr/lib/perl5/site_perl/5.26.2 /data/data/com.termux/files/usr/lib/perl5/5.26.2/arm-android /data/data/com.termux/files/usr/lib/perl5/5.26.2 .) at /data/data/com.termux/files/usr/share/Th3inspector/T

i tried googling
cpan install http/request.pm
or they said install clang 
they also said install make and i did but doesnt work
and they said install perl-libwww-perl or libwww-perl but
when i pkg install or apt get install. it says cannot locate package please help .

**Comment by Moham3dRiahi** [comment]
I will fix it soon
Thanks

**Comment by VictorH4C7** [comment]
After installing all the data I want farther information but it kept showing me there is a problem why
