### ISSUE TITLE
"There is a problem" Error on every search

### ISSUE THREAD

**Issue by DeShaunCarter** [Moham3dRiahi/Th3inspector#16]
Hi,

I'm getting this error for every option I pick. In this example, I searched for "google.com".

Note I'm running on Windows.

![image](https://user-images.githubusercontent.com/42100486/46912959-7d857900-cf51-11e8-8860-a214e2ffce7b.png)

Appreciate your time on this!

**Comment by Moham3dRiahi** [comment]
fixed

**Comment by tanvir3783** [comment]
It every time show there is a problem

**Comment by MrNobodyTharusha** [comment]
Yeh....
