### ISSUE TITLE
HTTP::Request module

### ISSUE THREAD

**Issue by 0x-MRNOBODY-x0** [Moham3dRiahi/Th3inspector#19]
[+] Installing ...
 [+] Creating Symbolic Link ...
 [+] Tool successfully installed and will start in 5s!
 [+] You can execute tool by typing Th3inspector
Can't locate HTTP/Request.pm in @INC (you may need to install the HTTP::Request module) (@INC contains: /data/data/com.termux/files/usr/lib/perl5/site_perl/5.28.1/aarch64-android /data/data/com.termux/files/usr/lib/perl5/site_perl/5.28.1 /data/data/com.termux/files/usr/lib/perl5/5.28.1/aarch64-android /data/data/com.termux/files/usr/lib/perl5/5.28.1 .) at /data/data/com.termux/files/usr/share/Th3inspector/Th3inspector.pl line 5.
BEGIN failed--compilation aborted at /data/data/com.termux/files/usr/share/Th3inspector/Th3inspector.pl line 5.
 ✘  ~/Th3inspector   master ● 

What can I do for it...???

**Comment by amulyk** [comment]
> [+] Installing ...
> [+] Creating Symbolic Link ...
> [+] Tool successfully installed and will start in 5s!
> [+] You can execute tool by typing Th3inspector
> Can't locate HTTP/Request.pm in @inc (you may need to install the HTTP::Request module) (@inc contains: /data/data/com.termux/files/usr/lib/perl5/site_perl/5.28.1/aarch64-android /data/data/com.termux/files/usr/lib/perl5/site_perl/5.28.1 /data/data/com.termux/files/usr/lib/perl5/5.28.1/aarch64-android /data/data/com.termux/files/usr/lib/perl5/5.28.1 .) at /data/data/com.termux/files/usr/share/Th3inspector/Th3inspector.pl line 5.
> BEGIN failed--compilation aborted at /data/data/com.termux/files/usr/share/Th3inspector/Th3inspector.pl line 5.
> ✘  ~/Th3inspector   master ● 
> 
> What can I do for it...???

1.  Run this command — apt-get install build-essential
2. Install the HTTP::Request module through cpan(m). See for example https://stackoverflow.com/questions/65865/whats-the-easiest-way-to-install-a-missing-perl-module.

**Comment by MrNobodyTharusha** [comment]
I'll try it

**Comment by MrNobodyTharusha** [comment]
Hay..... can't locate it.

~  apt-get install build-essential
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package build-essential

**Comment by COMBAT-OFFICIAL** [comment]
not working

**Comment by generaalbarcode** [comment]
:1st_place_medal: 

**First do  :  _1 Run this command — apt-get install build-essential_
Second  :  2 _./install.sh_**
