### ISSUE TITLE
Mac always  [there is A Problem]

### ISSUE THREAD

**Issue by CoColizdf** [Moham3dRiahi/Th3inspector#23]
I try somethings follow the video in youtube, but ........

perl Th3inspector.pl -i google.com

```
 [+] There Is A Problem

 [1] Checking The Connection
 [2] Enter Website Without HTTP/HTTPs
 [3] Check If Website Working

```
Then I try add sudo ,same result

I turn off the firewall in mac, same result 

I need help, how to solve the problem?

Thank you very much， the tools is pretty good .

**Comment by ccclement** [comment]
Hello.

I have a hypothesis:

The -i option will look for the information on the website https://myip.ms/.
This site happens to use a captcha to avoid the use of robots.
As a result, the Perl script can no longer retrieve information from the site.

**Comment by godeyes333** [comment]
Good
