### ISSUE TITLE
phone number infogathering not working

### ISSUE THREAD

**Issue by r3x07** [Moham3dRiahi/Th3inspector#25]
,;;;,     
        ;;;;;;;                   
     .- `\, '/_      _____ _    ____  _                      _            
   .'   \  (`(_)    |_   _| |_ |__ / (_)_ _  ____ __  ___ __| |_ ___ _ _ 
  / `-,. \ \_/        | | | ' \ |_ \ | | ' \(_-< '_ \/ -_) _|  _/ _ \ '_| 
  \  \/ \ `--`        |_| |_||_|___/ |_|_||_/__/ .__/\___\__|\__\___/_| V 1.9
   \  \  \                         [127.0.0.1] |_| [192.168.1.1] 
    / /| |                            [Coded BY Mohamed Riahi]
   /_/ |_|      
  ( _\ ( _\    #:##       #:##
                     #:## 

 [+] There Is A Problem

 [1] Checking The Connection
 [2] Enter Phone Number Without +/00
 [3] Check If Phone Number Exists

it always says that even with a valid phone number

**Comment by MonaKillah** [comment]
the same happens to me

**Comment by NT0X1N** [comment]
Did you ever fix the phone look up? Is it only with this version? Thanks.

**Comment by MonaKillah** [comment]
I tried it in the previous version and if it worked

**Comment by MonaKillah** [comment]
Several things do not work apart from the phone ...

**Comment by ODIN1488THOR** [comment]
Thanks for getting back to me and no I've tried alot of stuff and can't
figure out what the problem is

**Comment by djcurtin** [comment]
Manually working through phone number lookup routine gives this response from apilayer.net request:

{ "success":false, "error":{ "code":104, "type":"usage_limit_reached", "info":"Your monthly usage limit has been reached. Please upgrade your Subscription Plan." } }

Haven't used the application yet, so haven't read any instructions, but looks like the user should set up a personal apilayer access key.

**Comment by sundowndev** [comment]
Consider looking at [PhoneInfoga](https://github.com/sundowndev/PhoneInfoga) which has a correct implementation of this API.

**Comment by MaulanaDK** [comment]
i got the same problem sir

**Comment by deadfishhackers** [comment]
@sundowndev checked PhoneInfoga but couldnt find where the api is located

**Comment by sundowndev** [comment]
@deadfishhackers If you mean Numverify API, look at this file https://github.com/sundowndev/PhoneInfoga/blob/master/scanners/numverify.py

**Comment by deadfishhackers** [comment]
@sundowndev  Thanks!

**Comment by deadfishhackers** [comment]
@sundowndev still cant find api key

**Comment by sundowndev** [comment]
The API key is not hard coded, it's being scraped from the Numverify website itself. Numverify creates a "demo" token to be able to use their API on their homepage. This implementation was done by reverse engineering.
