### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by AHvibrator** [Moham3dRiahi/Th3inspector#26]
I use of termux in android
The error is :
Can't locate HTTP/Request.pm in @INC (you may need to install the HTTP::Request module) (@INC contains: /data/data/com.termux/files/usr/lib/perl5/site_perl/5.28.1/arm-android /data/data/com.termux/files/usr/lib/perl5/site_perl/5.28.1 /data/data/com.termux/files/usr/lib/perl5/5.28.1/arm-android /data/data/com.termux/files/usr/lib/perl5/5.28.1 .) at /data/data/com.termux/files/usr/share/Th3inspector/Th3inspector.pl line 5.
BEGIN failed--compilation aborted at /data/data/com.termux/files/usr/share/Th3inspector/Th3inspector.pl line 5.

**Comment by MamaWin** [comment]
Mine line 6

**Comment by AHvibrator** [comment]
nnnoooooo
when i enter command ./install i get this error :
Can't locate HTTP/Request.pm in @INC (you may need to install the HTTP::Request module) (@INC contains: /data/data/com.termux/files/usr/lib/perl5/site_perl/5.30.0/arm-android /data/data/com.termux/files/usr/lib/perl5/site_perl/5.30.0 /data/data/com.termux/files/usr/lib/perl5/5.30.0/arm-android /data/data/com.termux/files/usr/lib/perl5/5.30.0 .) at /data/data/com.termux/files/usr/share/Th3inspector/Th3inspector.pl line 5.
BEGIN failed--compilation aborted at /data/data/com.termux/files/usr/share/Th3inspector/Th3inspector.pl line 5.
What can i do help me

**Comment by lezohtml** [comment]
Hi there, 

I have the same issue on Ubuntu : 

Can't locate JSON.pm in @INC (you may need to install the JSON module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/Th3inspector/Th3inspector.pl line 18.
BEGIN failed--compilation aborted at /usr/share/Th3inspector/Th3inspector.pl line 18.

**Comment by mk-omg** [comment]
Same here
