### ISSUE TITLE
There Is A Problem!

### ISSUE THREAD

**Issue by PourLa** [Moham3dRiahi/Th3inspector#27]
fussed with a problem.
I get this error at all stages in the application.
Please help.

[+] There Is A Problem
[1] Checking The Connection
[2] Enter Website Without HTTP/HTTPs
[3] Check If Website Working
[+] Press [ENTER] Key To Continue

**Comment by ylchbe** [comment]
same here

**Comment by kenshinhimura** [comment]
The error is because the website 

    $url = "https://myip.ms/$site1";

have a captcha now, so first you have to do a request from your web browser, pass the captcha and then run tool again, the website only ask for captcha one time.

i hope this help

cheers.

**Comment by jordantsap** [comment]
Same here anyone with a solution??

**Comment by ODIN1488THOR** [comment]
No I've been waiting for months for someone to help me with it and I have
not got any responses on a solution I've just been receiving emails for
others like my self with same problem I have emailed the developer and
haven't heard anything either

**Comment by rudeboi9000** [comment]
I noticed this issue when using the phone number lookup option, and here is what I changed:
`sub Phonenumberinformation {

    $url = "https://pastebin.com/raw/egbm0eEk";
    $request = $ua->get($url);
    #$api2 = $request->content;
    $api2 = "<insert your API key here after you sign up for an account>";`

Go to http://apilayer.net/ and setup an account to hard code your API key. Maybe not best practice but it works.

**Comment by Zeus90** [comment]
I have the same as well
update command does not work as well
