### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by RamadhanP** [Moham3dRiahi/Th3inspector#30]
Can't locate HTTP/Request.pm in @INC (you may need to install the HTTP::Request module) (@INC contains: /data/data/com.termux/files/usr/lib/perl5/site_perl/5.30.0/aarch64-android /data/data/com.termux/files/usr/lib/perl5/site_perl/5.30.0 /data/data/com.termux/files/usr/lib/perl5/5.30.0/aarch64-android /data/data/com.termux/files/usr/lib/perl5/5.30.0 .) at Th3inspector.pl line 5.
BEGIN failed--compilation aborted at Th3inspector.pl lin

**Comment by baraasyria** [comment]
وأنا مثلك أيضاً

**Comment by Ragavan2003** [comment]
I too have a same problem.
