### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by loriezn** [Moham3dRiahi/Th3inspector#4]
malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "<!DOCTYPE html>\n<!-...") at /usr/share/Th3inspector/Th3inspector.pl line 1296.

when performing a credit card bin check.

**Comment by Moham3dRiahi** [comment]
Sorry for this issue. This issue fixed now in commit 13c0ef6 .

Please update to the latest version

**Comment by loriezn** [comment]
Thanks!
