### ISSUE TITLE
Subdomains checker does not find subdomains

### ISSUE THREAD

**Issue by SundownDEV** [Moham3dRiahi/Th3inspector#8]
```
$ perl Th3inspector.pl -s crvx.fr
```

```
[+] Website: crvx.fr
 [+] IP: 54.36.101.216

 [+] No Subdomains Found For This Domain
```

I don't know how do you check subdomains (can't contribute since I don't code in Perl), but this tool written in Python is working : https://github.com/UnaPibaGeek/ctfr it use certificate transparency logs to scan subdomains.

BTW still a very nice job! :)

**Comment by Moham3dRiahi** [comment]
will update ti thanx <3
